line-length = 100
target-version = "py313"
unsafe-fixes = true
src = ["src", "tests"]

[lint]
select = ["E", "F", "I", "UP", "B", "C4", "SIM", "RUF"]
ignore = ["E501"]

[lint.isort]
known-first-party = ["concordat"]
force-single-line = true
